id: IF3ACC3E1
initial_creation_type: ebook
source_metadata:
  id: LEK-KAR-15-3
  title: ༄༅། །དེ་བཞིན་གཤེགས་པའི་སྙིང་པོ་བསྟན་པའི་བསྟན་བཅོས་ཀྱི་མཆན་འགྲེལ་བྱམས་མགོན་དགྱེས་པའི་ཞལ་ལུང་ནོར་བུ་དབང་གི་རྒྱལ་པོ་དྲི་མ་མེད་པའི་འོད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  author: མཛད་པ་པོ། ཀརྨ་པ་མཁའ་ཁྱབ་རྡོ་རྗེ།
  authors: &id001
  - མཛད་པ་པོ། ཀརྨ་པ་མཁའ་ཁྱབ་རྡོ་རྗེ།
  sku: LEK-KAR-15-3
  cover: _LEK-KAR-15-3.jpg
  volume: {}
ebook_metadata:
  title: ༄༅། །དེ་བཞིན་གཤེགས་པའི་སྙིང་པོ་བསྟན་པའི་བསྟན་བཅོས་ཀྱི་མཆན་འགྲེལ་བྱམས་མགོན་དགྱེས་པའི་ཞལ་ལུང་ནོར་བུ་དབང་གི་རྒྱལ་པོ་དྲི་མ་མེད་པའི་འོད་ཅེས་བྱ་བ་བཞུགས་སོ།
    །
  authors: *id001
  sku: LEK-KAR-15-3
  cover: _LEK-KAR-15-3.jpg
layers:
- Author
- BookTitle
- Commentary
- Sabche
- Tsawa
